name: Test the workflow 
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install
      - run: npm test
        env:
          CI: true
      - run: npm run build
  sleep-time:
    name: sleep-time
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          time: '5m'
      - run: sleep 5m
