name: Test workflow 

on:
  workflow_dispatch:
    branches:
      - main
jobs:
  create-eod-stack:
    name: create eod stack
    runs-on: ubuntu-latest
    strategy:
      matrix:
        
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          
      - run: npm install
      - run: npm start
