name: Test the workflow 2
on:
  workflow_run:
    workflows: ['Test the workflow']
    types:
      [completed]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install
      - run: npm test
        env:
          CI: true
      - run: npm run build